### ISSUE TITLE
[RATE LIMIT] - Rate limited. Sleeping.

### ISSUE THREAD

**Issue by chenlyuzhao** [meet447/Reddit-Karma-Bot#5]
How should solve this? Is there some place I can increase my limit?

**Comment by meet447** [comment]
Reddit rate limits you for posting frequently try increasing the time between your posts

**Comment by chenlyuzhao** [comment]
thanks not it worked

**Comment by chenlyuzhao** [comment]
what would be the format of Proxy?
Is it host:ip:user:password?

**Comment by meet447** [comment]
ip:port:username:password

> what would be the format of Proxy? Is it host:ip:user:password?

**Comment by chenlyuzhao** [comment]
this is my code:
 
```
class Botconfig:
    proxies = [
        # Add more proxies as needed
        <ip>:6001:testtest222-zone-resi:testtest
    ]
```

but got error:
```
Traceback (most recent call last):
  File "C:\Users\67399\Desktop\Reddit-Karma-Bot-main\app.py", line 8, in <module>
    from config import Config, Botconfig
  File "C:\Users\67399\Desktop\Reddit-Karma-Bot-main\config.py", line 18
    43.159.20.169:6001:testtest222-zone-resi:testtest
    ^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Comment by chenlyuzhao** [comment]
I see i need to wrap with quotes ""..
Thanks

**Comment by meet447** [comment]
> I see i need to wrap with quotes ""..
> Thanks

You fixed it?
