### ISSUE TITLE
module 'g4f.Provider' has no attribute 'Vercel'

### ISSUE THREAD

**Issue by tgsAvylaar** [meet447/Reddit-Karma-Bot#6]
Hi, the script doesn't seem to be able to post any text, I get the below error.
I installed everything from requirements.txt

PS C:\Scripts\Reddit-Karma-Bot-main> python .\index.py
Version 7.7.1 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.
[PROCESSING POST] - 'Threw Him Like A Sack Of Potatoes'
[PROXY] - All proxies failed. Trying without proxy.
[LOGIN] - Attempting login for X
[LOGIN] - Logged in as X
An unexpected error occurred: module 'g4f.Provider' has no attribute 'Vercel'
NO_TEXT
[Replied to] - Threw Him Like A Sack Of Potatoes with None
[ACCOUNT COMPLETE] - Commented on post 'Threw Him Like A Sack Of Potatoes' with account X

**Comment by meet447** [comment]
Inside llm.py

Try replacing the old client to this

client = Client()

**Comment by Appilot-dev** [comment]
We have made a reddit bot in 2024 but it functions through your phone remotely with a web dashboard no ADB or wire needed, a reddit karma bot that mimics human behavior through a learning script for the bot that shadows different humanized ways of managing an account of reddit.
You can check it's commenting features in [our repository.](https://github.com/Appilot-dev/Reddit-Android-Karma-Farming-Bot)
How you can control the bot’s speed and never get banned again.
